version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - curl -sSL https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz | tar -xz -C /opt/
      - export PATH="/opt/apache-maven-3.8.4/bin:$PATH"
      - mvn --version

  build:
    commands:
      - echo "Building WAR file with Maven..."
      - mvn clean package
      
      - mkdir -p webapps
      - cp target/*.war webapps

      - mkdir -p webapps/ROOT
      - unzip -q target/*.war -d webapps/ROOT/

  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 sync webapps/ s3://map-ken-wuxi-s3-test/StringConvSoapclient/

artifacts:
  files:
    - webapps/**/*
  base-directory: webapps
  discard-paths: no
